window.ELEMENTOS = [
    {
        id: "na",
        nome: "Sódio",
        simbolo: "Na",
        numeroAtomico: 11,
        grupo: 1,
        periodo: 3,
        familia: "Metal alcalino",
        estado: "sólido",
        distribuicao: "2–8–1",
        configuracao: "1s² 2s² 2p⁶ 3s¹",
        valencia: "1 elétron de valência",
        ion: "Na⁺",
        marcador: "assets/marcadores/na.patt",
        modelo: "assets/modelos/na.glb",
        audio: "assets/audio/na.mp3"
    },
    {
        id: "mg",
        nome: "Magnésio",
        simbolo: "Mg",
        numeroAtomico: 12,
        grupo: 2,
        periodo: 3,
        familia: "Metal alcalino-terroso",
        estado: "sólido",
        distribuicao: "2–8–2",
        configuracao: "1s² 2s² 2p⁶ 3s²",
        valencia: "2 elétrons de valência",
        ion: "Mg²⁺",
        marcador: "assets/marcadores/mg.patt",
        modelo: "assets/modelos/mg.glb",
        audio: "assets/audio/mg.mp3"
    },
    {
        id: "al",
        nome: "Alumínio",
        simbolo: "Al",
        numeroAtomico: 13,
        grupo: 13,
        periodo: 3,
        familia: "Família do boro",
        estado: "sólido",
        distribuicao: "2–8–3",
        configuracao: "1s² 2s² 2p⁶ 3s² 3p¹",
        valencia: "3 elétrons de valência",
        ion: "Al³⁺",
        marcador: "assets/marcadores/al.patt",
        modelo: "assets/modelos/al.glb",
        audio: "assets/audio/al.mp3"
    },
    {
        id: "si",
        nome: "Silício",
        simbolo: "Si",
        numeroAtomico: 14,
        grupo: 14,
        periodo: 3,
        familia: "Família do carbono",
        estado: "sólido",
        distribuicao: "2–8–4",
        configuracao: "1s² 2s² 2p⁶ 3s² 3p²",
        valencia: "4 elétrons de valência",
        ion: "não forma íon simples comum",
        marcador: "assets/marcadores/si.patt",
        modelo: "assets/modelos/si.glb",
        audio: "assets/audio/si.mp3"
    },
    {
        id: "p",
        nome: "Fósforo",
        simbolo: "P",
        numeroAtomico: 15,
        grupo: 15,
        periodo: 3,
        familia: "Família do nitrogênio",
        estado: "sólido",
        distribuicao: "2–8–5",
        configuracao: "1s² 2s² 2p⁶ 3s² 3p³",
        valencia: "5 elétrons de valência",
        ion: "P³⁻ (fosfeto)",
        marcador: "assets/marcadores/p-v2.patt",
        modelo: "assets/modelos/p.glb",
        audio: "assets/audio/p.mp3"
    },
    {
        id: "s",
        nome: "Enxofre",
        simbolo: "S",
        numeroAtomico: 16,
        grupo: 16,
        periodo: 3,
        familia: "Calcogênios",
        estado: "sólido",
        distribuicao: "2–8–6",
        configuracao: "1s² 2s² 2p⁶ 3s² 3p⁴",
        valencia: "6 elétrons de valência",
        ion: "S²⁻ (sulfeto)",
        marcador: "assets/marcadores/s.patt",
        modelo: "assets/modelos/s.glb",
        audio: "assets/audio/s.mp3"
    }
];
